### ISSUE TITLE
关于METHOD_ANNOTATION_ONLY 的问题

### ISSUE THREAD

**Issue by pig4cloud** [Nepxion/Matrix#6]
老师你好！
我在执行源码中的测试用例的时候，不应该是只有 doC()方法被切嘛？

### 代码版本
clone 了最新master分支的代码
### 执行MyApplication2 
日志显示只扫描了  MyService2Impl.doC
![image](https://user-images.githubusercontent.com/12409311/49706054-3e785900-fc5e-11e8-8409-38e8eb067a49.png)

### 实际结果切刀  doD() 也被拦截器切到了
![image](https://user-images.githubusercontent.com/12409311/49706067-58b23700-fc5e-11e8-82e4-3040e4730fcd.png)
![image](https://user-images.githubusercontent.com/12409311/49706088-77183280-fc5e-11e8-8ca1-a208e51bce7a.png)

**Comment by HaojunRen** [comment]
他的含义是只有类里面还有某个注解，该类所有方法都会被代理，这是通用代理的机制

**Comment by pig4cloud** [comment]
thx
